version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: "Asia/Kolkata"
  allow:
    - dependency-type: "all"
  open-pull-requests-limit: 5
  target-branch: main
